version: '3.8'

services:

 ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    depends_on:
      - app
    networks:
      - api

 app:
    build: .
    ports:
      - '3000:3000'
    networks:
      - api
    volumes:
      - .:/app
      - /app/node_modules
      - ./tokens:/app/tokens

networks:
  api:
    name: api
    driver: bridge